# [START gae_python37_cloudsql_config]
runtime: python37

env_variables:
  CLOUD_SQL_USERNAME: connector
  CLOUD_SQL_PASSWORD: 123456789
  CLOUD_SQL_DATABASE_NAME: dem0
  CLOUD_SQL_CONNECTION_NAME: static-ceiling-361209:us-central1:vpconnector
# [END gae_python37_cloudsql_config]

vpc_access_connector: 
  name: "projects/static-ceiling-361209/locations/us-central1/connectors/connect-to-sql"